apiVersion: v1
kind: Service
metadata:
  name: default-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector: {}
  clusterIP: ""
  type: ClusterIP
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  healthCheckNodePort: 0
