apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: example
        spec:
          containers:
          - name: example-container
            image: example-image:latest
            command: ["echo", "Hello, World!"]
          restartPolicy: OnFailure
