apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 31000   # Exposed port for accessing the Node.js application
    targetPort: 80   # Port your Node.js application listens on inside the pod
  type: LoadBalancer   # Expose the service on a static port on each node
