apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: LoadBalancer
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080   # Port exposed by the service
      targetPort: 8080   # Port on which Tomcat is running inside the pod