---
- name: install docker requirements
  hosts: k8scontrollers, k8sworkers
  remote_user: admin

  tasks:
    - name: install install
      ansible.builtin.apt:
        name: install 
        state: latest
    - name: install curl
      ansible.builtin.apt:
        name: curl
        state: latest
    - name: install ca certificates
      ansible.builtin.apt:
        name: ca-certificates
        state: latest
    - name: install keyring file
      ansible.builtin.shell: install -m 0755 -d /etc/apt/keyrings
    - name: download docker keyring
      ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    - name: change file atributes
      ansible.builtin.shell: chmod a+r /etc/apt/keyrings/docker.asc
    - name: add docker entry to apt list
      ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: apt update
      ansible.builtin.shell: apt-get update